# **Introduction to Numpy**

In [5]:
# Import numpy
import numpy as np

### **Numpy Arrays**
An array is a multi-dimensional grid of values.


In [6]:
# Create an array from a list:
x_1d = np.array([1, 2, 3])
print(x_1d)

[1 2 3]


In [7]:
# This is like a lists of numbers
# We can print the first indices like [0] or the first 2 as [0,2]
print(x_1d[0])
print(x_1d[0:2])

1
[1 2]


Next, we define a 2-dimensional array (a matrix)


In [6]:
x_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Now when accesing a speicifc value x_2d[row , column]
print(x_2d[0,2])

# When if we want first row: x_23[row, :]
print(x_2d[0, :])

# When we want first column: x_2d[:, column]
print(x_2d[:, 1])

3
[1 2 3]
[2 5 8]


In [11]:
# Usefull arrays function:
zeroes = np.zeros(10)
ones = np.ones(10)
print(zeroes)
print(ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Operations:
1. Operations between an array and a number
2. Operations between two arrays of the same shape

In [14]:
# Operations
print(zeroes + 2)
print(ones -1 )

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### **Universal functions**

In [15]:
# Linspace(l_bound, u_bound, numbers)
x = np.linspace(0,10,10)
print(x)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
